VTS_Admin_Portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
      
       path('', views.login_view, name='login'),

   path('login/', views.login_view, name='login'),

   path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),

   
    path('dashboard/designer/', views.designer_dashboard, name='designer_dashboard'),
    path('developer_dashboard/', views.developer_dashboard, name='developer_dashboard'),
    path('dashboard/designer-trainee/', views.designer_trainee_dashboard, name='designer_trainee_dashboard'),
    path('dashboard/developer-trainee/', views.developer_trainee_dashboard, name='developer_trainee_dashboard'),

    path('logout/', views.admin_logout, name='admin_logout'),
      path('developer_list/', views.developer_list_view, name='developer_list'),
     path('trainers/add/', views.trainer_form_view, name='add_trainer'),
    path('trainers/<int:trainer_id>/edit/', views.trainer_form_view, name='edit_trainer'),
    path('trainers/<int:trainer_id>/delete/', views.trainer_delete_view, name='delete_trainer'),


path('trainees/trainee_card_view', views.trainee_card_view, name='trainee_card_view'),
     path('trainees/', views.trainee_list_view, name='trainee_list'),
    path('trainees/add/', views.trainee_form_view, name='add_trainee'),
    path('trainees/<int:trainee_id>/edit/', views.trainee_form_view, name='edit_trainee'),
    path('trainees/<int:trainee_id>/delete/', views.trainee_delete_view, name='delete_trainee'),

     path('exams/exam_list/', views.exam_list, name='exam_list'),
     path('exams/add/', views.add_exam, name='add_exam'),
    path('exams/<int:exam_id>/edit/', views.edit_exam, name='edit_exam'),
    path('exams/<int:exam_id>/delete/', views.delete_exam, name='delete_exam'),
    path('exams/add_exam_question_form/', views.add_exam_question_form, name='add_exam_question_form'),

    
path('exams/edit_exam_question_form/<int:question_id>/', views.edit_exam_question_form, name='edit_exam_question_form'),
    
    path('exams/add-question/', views.add_exam_question, name='add_exam_question'),
     path('questions/<int:question_id>/delete/', views.delete_exam_question, name='delete_question'),

      path('practicalquestions/', views.practical_question_list, name='practical_question_list'),
    path('practicalquestions/delete/<int:pk>/', views.delete_practical_question, name='delete_practical_question'),
    path('practical_answer_list/<int:question_id>/', views.practical_answer_list, name='practical_answer_list'),


     path('courses/course_list', views.course_list, name='course_list'),
    path('courses/add/', views.add_course, name='add_course'),
    path('courses/edit/<int:course_id>/', views.edit_course, name='edit_course'),
     path('courses/<int:pk>/delete/', views.delete_course, name='delete_course'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('VTS_Admin_Portal.urls')), 
    path('', include('VTS_Developer_Trainee_Portal.urls')), 
    path('', include('VTS_Developer_Portal.urls')), 

    path('', include('exam.urls')), 
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('exams/add/', views.create_exam, name='create_exam'),
    path('exams/<int:exam_id>/add-question/', views.add_exam_question, name='add_exam_question'),
   
    path('exams/available/', views.available_exams, name='available_exams'),
    path('exams/<int:exam_id>/start/', views.start_exam, name='start_exam'),
    path('exams/<int:exam_id>/submit/', views.submit_exam, name='submit_exam'),

    path('exam/results/', views.exam_result_list, name='exam_result_list'),
    # path('exam/results/<int:exam_id>/', views.exam_result_list, name='exam_result_list'),


]

VTS_Admin_Portal/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from datetime import timedelta, date

from django.conf import settings 



class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email is required")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('role', 'admin')
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    ROLE_CHOICES = [
        ('designer', 'Designer'),
        ('developer', 'Developer'),
        ('designer_trainee', 'Designer Trainee'),
        ('developer_trainee', 'Developer Trainee'),
        ('admin', 'Admin'),
    ]

    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=100)
      
    mobile = models.CharField(max_length=15, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    role = models.CharField(max_length=30, choices=ROLE_CHOICES)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name', 'role']

    objects = UserManager()

    def __str__(self):
        return self.email
    
from django.db import models
from django.contrib.auth.models import User

class Trainer(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]

    EXPERTISE_CHOICES = [
        ('Designing', 'Designing'),
        ('frontend', 'Frontend'),
        ('backend', 'Backend'),
        ('fullstack', 'Fullstack'),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='trainer_profile')

    # Personal Info (in User model: mobile and profile_image)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    dob = models.DateField(verbose_name='Date of Birth', blank=True, null=True)

    # Expertise & Skills
    expertise_area = models.CharField(max_length=20, choices=EXPERTISE_CHOICES)
    experience_years = models.PositiveIntegerField(default=0)

    technical_languages = models.TextField(
        help_text="Enter comma-separated languages like: Python, Angular, React"
    )

    # Address
    address_line1 = models.CharField(max_length=255, verbose_name='Address Line 1', blank=True)
    address_line2 = models.CharField(max_length=255, verbose_name='Address Line 2', blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=100, default='India')

    # Status
    is_active = models.BooleanField(default=True)
    date_joined = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.full_name} ({self.get_expertise_area_display()})"

    def get_technical_languages_list(self):
        return [lang.strip() for lang in self.technical_languages.split(',') if lang.strip()]

class Course(models.Model):
    CATEGORY_CHOICES = [
        ('design', 'Design'),
        ('development', 'Development'),
        ('fullstack', 'Fullstack'),
        ('softskills', 'Soft Skills'),
    ]

    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    
    duration_weeks = models.PositiveIntegerField(help_text="Duration in weeks")
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(blank=True, null=True)
    
    
    fee = models.DecimalField(max_digits=8, decimal_places=2, help_text="Course fee in INR")

    trainer = models.ForeignKey('Trainer', on_delete=models.SET_NULL, null=True, blank=True, related_name='courses')

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.start_date  :
            self.end_date = self.start_date + timedelta(weeks=self.duration_weeks)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def duration_display(self):
        return f"{self.duration_weeks} week(s)"      





class Trainee(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    CLASS_MODE_CHOICES = [
        ('online', 'Online'),
        ('offline', 'Offline'),
    ]


    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='trainee_profile')

    # Personal Info
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    dob = models.DateField(verbose_name='Date of Birth', blank=True, null=True)

    
    class_mode = models.CharField(
        max_length=10,
        choices=CLASS_MODE_CHOICES,
        default='online'
    )

    # Course & Trainer Info (optional foreign keys)
    assigned_course = models.ForeignKey('Course', on_delete=models.SET_NULL, null=True, blank=True, related_name='trainees')
    assigned_trainer = models.ForeignKey('Trainer', on_delete=models.SET_NULL, null=True, blank=True, related_name='trainees')
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(blank=True, null=True)
    # Address
    address_line1 = models.CharField(max_length=255, blank=True)
    address_line2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=100, default='India')

    # Status
    is_active = models.BooleanField(default=True)
    date_joined = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.start_date and self.assigned_course :
            self.end_date = self.start_date + timedelta(weeks=self.assigned_course.duration_weeks)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.full_name

    def get_full_address(self):
        return f"{self.address_line1}, {self.address_line2}, {self.city}, {self.state} - {self.postal_code}, {self.country}"

VTS_Admin_Portal/templates/VTS_Admin_Portal/add_question.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'VTS_Admin_Portal/css/add_question.css' %}">
{% endblock %}

{% block content %}
<div class="form-container">
  <h2>Add New Question</h2>
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label>Exam</label>
      {{ form.exam }}
    </div>
    <div class="form-group">
      <label>Question</label>
      {{ form.question_text }}
    </div>
    <div class="form-group">
      <label>Option A</label>
      {{ form.option_a }}
    </div>
    <div class="form-group">
      <label>Option B</label>
      {{ form.option_b }}
    </div>
    <div class="form-group">
      <label>Option C</label>
      {{ form.option_c }}
    </div>
    <div class="form-group">
      <label>Option D</label>
      {{ form.option_d }}
    </div>
    <div class="form-group">
      <label>Correct Option</label>
      {{ form.correct_option }}
    </div>

    <div class="button-group">
      <button type="submit" class="submit-btn">{% if mode == 'Edit' %} Update {% else %} + Add question {% endif %}</button>
    </div>
  </form>
  <div class="button-group">
      <a href="{% url 'exam_list' %}" class="cancel-btn">Cancel</a>
    </div>
</div>


{% endblock %}

VTS_Admin_Portal/templates/VTS_Admin_Portal/admin_add_edit_exam.html
{% extends 'core/base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'VTS_Admin_Portal/css/exam_form.css' %}">
{% endblock %}

{% block content %}
<div class="exam-form-container">
  
  <h2 class="form-title">{{ mode }} Exam</h2>
  <form method="POST">
    {% csrf_token %}
    <div class="form-grid">
      {{ form.course.label_tag }} {{ form.course }}
      {{ form.title.label_tag }} {{ form.title }}
      {{ form.description.label_tag }} {{ form.description }}
      {{ form.date.label_tag }} {{ form.date }}
      {{ form.start_time.label_tag }} {{ form.start_time }}
      {{ form.duration_minutes.label_tag }} {{ form.duration_minutes }}
      {{ form.total_marks.label_tag }} {{ form.total_marks }}

          



    </div>
<div class="action-box">
    <h4 class="action-title"> {{ form.isActivate.label }}</h4>
    <div class="action-row">
        <label>{{ form.isActivate }}  YES</label>
    </div>
</div>


    <button type="submit" class="submit-btn" onclick="this.disabled=true; this.form.submit();">
    {% if mode == 'Edit' %} Update {% else %} Add {% endif %}

    </button>
    
  </form>

  <button class="submit-btn" style="background-color: #888888;"><a style="text-decoration: none !important; 
  color: inherit !important;" href="{% url 'exam_list' %}">Cancel</a></button>
    
</div>
<hr>
<div class="question-list-container">
  <div class="header">
    <h2>Questions for: {{ exam.title }}</h2>
    <a href="{% url 'add_exam_question_form' %}?exam_id={{ exam.id }}" class="add-btn">+ Add Question</a>
  </div>

  <div class="question-table">
    <table>
      <thead>
        <tr>
          <th>Question</th>
          <th>Option A</th>
          <th>Option B</th>
          <th>Option C</th>
          <th>Option D</th>
          <th>Correct</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for q in questions %}
        <tr>
          <td>{{ q.question_text }}</td>
          <td>{{ q.option_a }}</td>
          <td>{{ q.option_b }}</td>
          <td>{{ q.option_c }}</td>
          <td>{{ q.option_d }}</td>
          <td>{{ q.correct_option }}</td>
          <td>
            <a href="{% url 'edit_exam_question_form' q.id %}" class="edit-icon">

              <i class="fas fa-edit action-icon" style="color: rgb(130, 110, 245);"></i>
            </a>&nbsp;
            <a href="{% url 'delete_question' q.id %}" class="delete-icon" title="Delete"
   onclick="return confirm('Are you sure you want to delete this question?');">
<i class="fas fa-trash-alt action-icon" style="color: rgb(244, 74, 74);"></i>            </a>

             
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="7">No questions found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}


{% endblock %}

VTS_Admin_Portal/templates/VTS_Admin_Portal/course_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_css %}
<link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'VTS_Admin_Portal/css/trainer_form.css' %}">
{% endblock %}

{% block content %}
<div class="trainer-form-container">
  <h2>{{ is_edit|yesno:"Edit Course,Add Course" }}</h2>

  <form method="POST" enctype="multipart/form-data" class="trainer-form">
    {% csrf_token %}
    <div class="form-grid">
      {% for field in form %}
        <div class="form-group">
          {{ field.label_tag }}
          {{ field }}
            {% if field.errors %}
  <div class="error" id="{{ field.id_for_label }}-error">{{ field.errors }}</div>
{% endif %}
        </div>
      {% endfor %}
    </div>

    <div class="form-actions">
              <button class="submit-btn" style="background-color: #888888;"><a href="{% url 'course_list' %}?role={{selected_role}}" class="menu-link">Cancel</a></button>

      <button type="submit" class="submit-btn">
        {{ is_edit|yesno:"Update,Add" }}
      </button>
    </div>
  </form>
</div>
{% endblock %}

VTS_Admin_Portal/templates/VTS_Admin_Portal/course_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'VTS_Admin_Portal/css/developer_list.css' %}">
{% endblock %}

{% block content %}

<div class="admin-dashboard-header">
  <!-- Part 1: Greeting -->
 <div class="greeting">
  <h3>{{ greeting }}!!!</h3>
  <p>It's {{ today|date:"l, d F Y" }}</p>
</div>

  <!-- Part 2: Search Box -->
  <!-- <div class="search-box">
    <input type="text" placeholder="Search Trainees..." />
    <div class="search-icon">
      <img src="{% static 'images/search.png' %}" alt="Search Icon" />
    </div>
  </div> -->

  <div class="search-box">
  <form method="get" action="{% url 'course_list' %}">
    <input
      type="text"
       autocomplete="off"
      name="c" 
      placeholder="Search Course..."
      value="{{ search_course }}"
    />
    
    <!-- Keep the role as hidden so it's not lost on search -->

    <div class="search-icon">
      <button type="submit" style="background: none; border: none;">
        <img src="{% static 'images/search.png' %}" alt="Search Icon" />
      </button>
    </div>
  </form>
</div>


  <!-- Part 3: Notification & Login -->
  <div class="icon-group">
    <!-- <div class="notification-icon">
      <img src="{% static 'images/notifi.jpg' %}" alt="Notifications" />
      <span class="badge">3</span>
    </div> -->
    <div class="login-icon">
      <a href="{% url 'admin_logout' %}">
      <img src="{% static 'images/logout.jpeg' %}" alt="User Login" title="logout"/>
      </a>
    </div>
  </div>
</div>

<div class="trainer-table-section">
  <div class="table-header">
    <h3>Course List</h3>

<!-- <button id="filterBtn" class="add-btn filter-btn" style="display: flex; flex-direction: row; gap: 15px; font-size: 16px;">
  <img src="{% static 'images/filter.png' %}" style="background-color: #ffffff;" alt="Filter Icon" />
  Filter
</button> -->
    <a  href="{% url 'add_course' %}" class="add-btn">+ Add Course</a>
  </div>

  <div class="table-responsive">
    <table class="trainer-table">
      <thead>
        <tr>
           <th>Name</th>
                <th>Category</th>
                <th>Trainer</th>
                <th>Start</th>
                <th>End</th>
                <th>Fee</th>
                <th>Action</th>
        </tr>
      </thead>
      <tbody>
       {% for course in courses %}
        <tr>
            <td>{{ course.name }}</td>
                <td>{{ course.get_category_display }}</td>
                <td>{{ course.trainer }}</td>
                <td>{{ course.start_date }}</td>
                <td>{{ course.end_date }}</td>
                <td>₹{{ course.fee }}</td>
                <td>
                    <a href="{% url 'edit_course' course.id %}"><i class="fas fa-edit action-icon" style="color: rgb(130, 110, 245);"></i></a> &nbsp;
                

           <a href="{% url 'delete_course' pk=course.id %}"
   class="delete-icon"
   title="Delete"
   onclick="return confirm('Are you sure you want to delete this course?');">
   <i class="fas fa-trash-alt action-icon" style="color: rgb(244, 74, 74);"></i>
</a>

          </td>
        </tr>
        {% empty %}
        <tr><td colspan="8">No Couse found.</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div id="filterModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2 style="margin-bottom: 20px;">Filter by</h2>

    <form method="get" action="{% url 'trainee_card_view' %}">
      <div class="form-group">
        <label for="class_mode">Class Mode</label>
       <select name="class_mode" id="class_mode">
  <option value="">-- Select --</option>
  <option value="online" {% if selected_class_mode == 'online' %}selected{% endif %}>Online</option>
  <option value="offline" {% if selected_class_mode == 'offline' %}selected{% endif %}>Offline</option>
</select>
      </div>

      <div class="form-group">
        <label for="course">Course</label>
        <select name="course" id="course">
  <option value="" disabled selected>__Select a Course__</option>
  {% for c in course %}
    <option value="{{ c.id }}" {% if c.id|stringformat:"s" == selected_course_id %}selected{% endif %}>{{ c.name }}</option>
  {% endfor %}
</select>
      </div>

      <div class="form-group">
       <label for="trainer">Trainer</label>
<select name="trainer" id="trainer">
  <option value="" disabled selected>__Select a Trainer__</option>
  {% for t in trainers %}
    <option value="{{ t.id }}" {% if t.id|stringformat:"s" == selected_trainer_id %}selected{% endif %}>{{ t.user.full_name }}</option>
  {% endfor %}
</select>
      </div>

      <!-- <div class="form-group">
        <label for="duration">Duration (weeks)</label>
        <input type="number" name="duration" id="duration" min="1" placeholder="Enter number of weeks" />
      </div> -->

      <button type="submit" class="submit-btn">Apply Filters</button>
    </form>
  </div>
</div>



{% endblock %}

VTS_Admin_Portal/templates/VTS_Admin_Portal/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Login</title>
  <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'VTS_Admin_Portal/css/login.css' %}">
</head>
<body>
  <div class="login-container">
    <h2> Login</h2>
    
    {% if messages %}
      <div class="error-box">
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %}
      </div>
    {% endif %}
    
    <form method="POST">
      {% csrf_token %}
      
      <label for="username">Email Address</label>
      <input type="text" id="username" name="username" placeholder="Enter your email Id" required>

      <label for="password">Password</label>
      <input type="password" id="password" name="password" placeholder="Enter your password" required>

      <button type="submit">Login</button>
    </form>
  </div>
</body>
</html>

VTS_Admin_Portal/templates/VTS_Admin_Portal/trainee_card_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'VTS_Admin_Portal/css/trainee_card_list.css' %}">
{% endblock %}

{% block content %} 
<div class="trainee-list-section">
  <div class="section-header">
<h3>
    Trainee List
    {% if selected_class_mode %}
        > {{ selected_class_mode }}
    {% endif %}
</h3>
    <!-- <a href="{% url 'add_trainee' %}" class="add-btn">+ Add Trainee</a> -->
  </div>

  <div class="trainee-card-container">
    {% for trainee in trainees %}
    <div class="trainee-card">
      <div class="top-row">
{% if trainee.user.profile_image %}
  <img src="{{ trainee.user.profile_image.url }}" alt="Trainee" style="width: 80px; height: 80px; margin-left: 16px; border-radius: 50%;">
{% else %}
  <img src="{% static 'images/img 1.png' %}" alt="Default Profile" style="width: 80px; height: 80px; margin-left: 16px; border-radius: 50%;">
{% endif %}        <div class="top-details">
          <p class="trainee-name">{{ trainee.user.full_name }}</p>
          <div class="action-icons" style="margin-top: -42px;">
            <a href="{% url 'edit_trainee' trainee.id %}?role={{selected_role}}" title="Edit">
            <img src="{% static 'images/edit.png' %}" alt="Edit" class="action-icon edit-icon">
            </a>
            <!-- <a href="{% url 'delete_trainee' trainee.id %}?role={{selected_role}}" title="Delete" onclick="return confirm('Are you sure?');">
              <i class="fas fa-trash-alt action-icon" style="color: rgb(244, 74, 74);"></i>
            </a> -->
          </div>
        </div>
      </div>

      <div class="middle-info">
        <p><strong>Duration :</strong><bold> {{ trainee.assigned_course.duration_weeks }} - weeks </bold></p>
        <p><strong>Course Name :</strong><bold> {{ trainee.assigned_course }}</bold></p>
        <p><strong>Class Mode :</strong><bold> {{ trainee.get_class_mode_display }}</bold></p>
      </div>

      <div class="bottom-info">
        <p style="margin-left: 22px;">            <img src="{% static 'images/Mail id.png' %}" alt="Edit" class="action-icon edit-icon" style="margin-right: 8px; vertical-align: middle;"
>
{{ trainee.user.email }}</p>
        <p style="margin-left: 22px;">            <img src="{% static 'images/Phone.png' %}" alt="Edit" class="action-icon edit-icon" style="margin-right: 8px; vertical-align: middle;"
>
 {{ trainee.user.mobile }}</p>
       <div id="view_more" style="margin-top: -38px;">
      
        <button 
    class="view_more" 
    onclick="openTraineeModal(
        '{{ trainee.user.full_name }}',
        '{{ trainee.get_gender_display }}',
        '{{ trainee.dob }}',
        '{{ trainee.get_class_mode_display }}',
        '{{ trainee.assigned_course }}',
        '{{ trainee.assigned_trainer }}',
        '{{ trainee.start_date }}',
        '{{ trainee.end_date }}',
        '{{ trainee.address_line1 }} {{ trainee.address_line2 }}, {{ trainee.city }}, {{ trainee.state }}, {{ trainee.postal_code }}, {{ trainee.country }}',
        '{{ trainee.is_active }}',
        '{{ trainee.date_joined }}',
        '{{ trainee.user.profile_image.url }}'
    )" >
    View more
</button>  



      </div>
      </div>
     
    </div>
    {% empty %}
      <p>No trainees found.</p>
    {% endfor %}
  </div>
</div>


<div id="traineeModal" class="modal" >
  <div class="modal-content">
    <span class="close" onclick="closeModal()">&times;</span>
    <div class="profile-pic">
      <img id="modalImage" src="" alt="Trainee Image">
    </div>
    <div class="trainee-info">
      <h2 id="modalName"></h2>
      <table class="trainee-table">
    <tbody>
      <tr>
        <td>Gender</td>
        <td id="modalGender"></td>
      </tr>
      <tr>
        <td>Date of Birth</td>
        <td id="modalDob"></td>
      </tr>
      <tr>
        <td>Class Mode</td>
        <td id="modalClassMode"></td>
      </tr>
      <tr>
        <td>Assigned Course</td>
        <td id="modalCourse"></td>
      </tr>
      <tr>
        <td>Assigned Trainer</td>
        <td id="modalTrainer"></td>
      </tr>
      <tr>
        <td>Start Date</td>
        <td id="modalStartDate"></td>
      </tr>
      <tr>
        <td>End Date</td>
        <td id="modalEndDate"></td>
      </tr>
      <tr>
        <td>Address</td>
        <td id="modalAddress"></td>
      </tr>
      <tr>
        <td>Is Active</td>
        <td id="modalStatus"></td>
      </tr>
      <!-- <tr>
        <td>Date Joined</td>
        <td id="modalDateJoined"></td>
      </tr> -->
    </tbody>
  </table>
    </div>
  </div>
</div>



{% endblock %}